README.md

fix the CI pipeline badge url
**Tick the relevant boxes:**
Merge using "Squash and merge" and ensure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message based on the PR contents (this ultimately determines if a new version of the modules needs to be released, and if so, which semver number should be used).

docs: fix the CI pipeline badge url

---

tests/go.mod

fix the module name in go.mod
**Tick the relevant boxes:**
Merge using "Squash and merge" and ensure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message based on the PR contents (this ultimately determines if a new version of the modules needs to be released, and if so, which semver number should be used).

tests: fix the module name in go.mod

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

- Editorial updates for style
- Remove TOC because it's generated by GH
- Change from 3rd person to 2nd person (you)
- Update PR template to match module-templatehange.
**Tick the relevant boxes:**
Merge using "Squash and merge" and ensure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message based on the PR contents (this ultimately determines if a new version of the modules needs to be released, and if so, which semver number should be used).

docs: Update readme and PR template

---

.github/workflows/release.yml
.releaserc
catalogValidationValues.json.template

Setup files for catalog onboard

ci: onboard to catalog

---

.releaserc

ci: add missing "v" to .releaserc

---

dynamic_values/address_prefixes.tf
main.tf
subnet.tf

Add tags to resources along with the address prefix fix

feat: add vpc tags for resources and prefix fix

---

.releaserc

This module is already approved for IBMers should should have `--target=ibm`

Update .releaserc -> --target=ibm

---

.releaserc

add --use_default_targz to .releaserc

ci: add --use_default_targz to .releaserc

---

variables.tf

Fix terraform_deprecated_index tflint rule

fix: address tflint terraform_deprecated_index rule

---

.github/settings.yml

Adds the repo name and description properties and values. 
See related [PR for VSI](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/pull/120)

ci: (settings) set name and description

---

.releaserc

The command was using old syntax
---

ci: fix the command in .releaserc to publish to catalog

---

.gitignore
.gitmodules

Couple of minor updates as I was working with this module: Ignore vscode + pin submodule to main branch
---

build: ignore vscode files

---

README.md

change usage example in readme file from `master` to `main`
cc @kbiegert 
---

docs: update branch in usage

---

.github/settings.yml

fixed the name of the repo in settings.yml file
---

docs: fixed the name in settings.yml

---

.releaserc

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
---

ci: stop publishing to catalog

---

README.md
examples/no-prefix/README.md
examples/no-prefix/main.tf
examples/no-prefix/outputs.tf
examples/no-prefix/provider.tf
examples/no-prefix/variables.tf
examples/no-prefix/version.tf
tests/go.mod
tests/pr_test.go

pr_test.go was updated to include a new test that ensures the prefix can be set to null. A new example was added to be used in this test. The example has the prefix hard-coded as null.
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- …

test: added a new test to ensure null prefix works

---

.github/workflows/ci.yml
cra-config.yaml
cra-tf-validate-ignore-rules.json

new cra config
```
/run pipeline
```

chore: cra config

---

examples/default/variables.tf

Resolves: https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/812
```
/run pipeline
```

fix: update cos plan condition

---

.github/settings.yml

This PR is to correct the description in the about section of this module. Corrected the module description to clarify it only provisions VPC resources, not virtual servers.
[Git_Issue](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/894)
Corrected the module description to clarify it only provisions VPC resources, not virtual servers.
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merg …

docs : Changed description

---

examples/landing_zone/main.tf

update variable type because of change in dependent module (transit-gateway)
Issue: https://github.ibm.com/GoldenEye/issues/issues/12896
uUpdate variable type because of change in dependent module (transit-gateway)
```
/run pipeline
```
- …

test: update variable type because of change in dependent module

---

solutions/fully-configurable/DA_docs.md

Documentation for VPC DA

---

main.tf
solutions/fully-configurable/main.tf

Scope auth policy for flow logs to exact cos bucket
[Issue](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/940)
Scope auth policy VPC to COS to exact cos bucket for flow logs collector
```
/run pipeline
``` …

feat: Scope auth policy for flow logs to exact cos bucket

---

ibm_catalog.json

Issue: #950 
Add `support details` section in catalog configuration for experimental tile.
```
/run pipeline
```

fix: add `support details` section in catalog configuration

---

solutions/fully-configurable/README.md
solutions/fully-configurable/version.tf

`1.78.2` is required to pick up the fix for https://github.com/IBM-Cloud/terraform-provider-ibm/pull/6235
```
/run pipeline
```

fix(deps): update DA provider version to 1.78.2

---

tests/pr_test.go

test: added flow logs test case
[Issue](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/989)
```
/run pipeline
```

test: added flow logs test case

---

tests/pr_test.go

flow logs upgrade test
[Issue](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/989)
```
/run pipeline
```

test: flow logs upgrade test
